development:
  adapter: postgresql
  encoding: unicode
  database: contactbook_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: contactbook_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: contactbook_production
  username: postgres
  password: 12345
  host: localhost
  port: 5432